# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk:
  - oraclejdk8

cache:
  directories:
      - '$HOME/.m2/repository'

install: true
script: 
  - mvn clean install
